# Generated by Django 5.0.6 on 2024-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.TextField(max_length=10, verbose_name='tên ngắn page')),
                ('pancake_id', models.TextField(max_length=20, verbose_name='id trang theo Pancake')),
                ('facebook_id', models.TextField(blank=True, max_length=20, verbose_name='id trang Facebook')),
                ('name', models.TextField(blank=True, verbose_name='tên trang')),
                ('url', models.TextField(blank=True, verbose_name='địa chỉ trang')),
                ('owner', models.TextField(blank=True, verbose_name='tên người sở hữu trang')),
                ('access_token', models.TextField(blank=True, verbose_name='access token của page')),
            ],
        ),
    ]
