# Generated by Django 5.0.6 on 2024-06-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='tên danh sách page')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='access token của page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=10, verbose_name='tên ngắn page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='id trang Facebook'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='tên trang'),
        ),
        migrations.AlterField(
            model_name='page',
            name='owner',
            field=models.CharField(blank=True, max_length=200, verbose_name='tên người sở hữu trang'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pancake_id',
            field=models.CharField(max_length=20, verbose_name='id trang theo Pancake'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='địa chỉ trang'),
        ),
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.group', verbose_name='thuộc nhóm'),
        ),
    ]
