# Generated by Django 5.0.6 on 2024-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_group_alter_page_access_token_alter_page_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='tên nhóm page'),
        ),
    ]
