# Generated by Django 5.0.6 on 2024-06-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Nhóm trang', 'verbose_name_plural': 'Nhóm trang'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Trang', 'verbose_name_plural': 'Trang'},
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=200, verbose_name='tên nhóm trang'),
        ),
        migrations.AlterField(
            model_name='page',
            name='code',
            field=models.CharField(max_length=10, verbose_name='tên ngắn page (tự đặt)'),
        ),
    ]
